version: "3.7"

services:
  db:
    env_file:
      - '.env'
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    # logging:
    #    driver: none
    ports:
      - "3307:3306"
  web_admin:
    container_name: admin_app
    env_file:
      - '.env'
    build: ./doc_admin
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: ${RAILS_ENV}
    ports:
      - "4000:4000"
    volumes:
      - ./doc_admin:/web_admin
    depends_on:
      - db
  web_api:
    container_name: api_app
    env_file:
      - '.env'
    build: ./doc_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: ${RAILS_ENV}
    ports:
      - "3000:3000"
    volumes:
      - ./doc_api:/web_api
    depends_on:
      - db
      - nginx
  web_react:
    container_name: react_app
    build: ./doc_react
    ports:
      - "3001:3001"
    depends_on:
      - web_api
  cache:
    container_name: memcached
    image: ubuntu/memcached:1.6-22.04_beta
    ports:
      - "11211:11211"
    restart: always
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - web_admin
  
volumes:
  dbdata: